CREATE TABLE T_USER
(  
  USER_ID          VARCHAR(32) NOT NULL COMMENT '用户ID',
  USER_NAME      VARCHAR(32) COMMENT '用户名',
  PASSWORD    VARCHAR(32) COMMENT '密码',
  AGE            INT COMMENT '年龄',
  BIRTHDAY       DATE COMMENT '出生日期',
  PRIMARY KEY (USER_ID)
);

ALTER TABLE T_USER COMMENT '测试用户表';